cities:
  newdelsta:
    check_points:
    - id: 1
      item_pos:
      - backup_pos: []
        pos:
        - 1169
        - 280
      - backup_pos: []
        pos:
        - 316
        - 352
      next_point: false
      pos:
      - 420
      - 615
      reset_map: true
    - id: 2
      item_pos:
      - backup_pos: []
        pos:
        - 561
        - 239
      - backup_pos: []
        pos:
        - 260
        - 388
      next_point: false
      pos:
      - 533
      - 617
      reset_map: true
    - id: 3
      item_pos:
      - backup_pos: []
        pos:
        - 732
        - 378
      next_point: true
      pos:
      - 590
      - 444
      reset_map: true
    - id: 4
      item_pos:
      - backup_pos: []
        pos:
        - 75
        - 377
      next_point: true
      pos:
      - 557
      - 259
      reset_map: true
    - id: 5
      item_pos:
      - backup_pos: []
        pos:
        - 724
        - 321
      - backup_pos: []
        pos:
        - 507
        - 539
      next_point: false
      pos:
      - 675
      - 289
      reset_map: false
    - id: 6
      item_pos:
      - backup_pos: []
        pos:
        - 635
        - 397
      next_point: true
      pos:
      - 815
      - 324
      reset_map: true
    - id: 7
      item_pos:
      - backup_pos: []
        pos:
        - 868
        - 385
      next_point: true
      pos:
      - 804
      - 504
      reset_map: true
    - id: 8
      item_pos:
      - backup_pos: []
        pos:
        - 639
        - 357
      next_point: true
      pos:
      - 720
      - 500
      reset_map: true
    - id: 9
      item_pos:
      - backup_pos: []
        pos:
        - 623
        - 385
      next_point: true
      pos:
      - 753
      - 621
      reset_map: true
    - id: 10
      item_pos:
      - backup_pos: []
        pos:
        - 398
        - 420
      next_point: true
      pos:
      - 647
      - 619
      reset_map: true
    entrance_pos:
    - 337
    - 596
    inn_pos:
    - 645
    - 573
    monsters:
    - battle_config: ''
      name: 逢魔精英怪
      points:
      - - 292
        - 457
        - '170012'
        - 5
      - - 333
        - 493
        - 317E36
        - 5
      - - 415
        - 493
        - '348036'
        - 5
      - - 270
        - 447
        - 949E96
        - 5
    - battle_config: ''
      name: 逢魔Boss
      points:
      - - 402
        - 538
        - 3B7B3E
        - 5
      - - 321
        - 539
        - 337F35
        - 5
      - - 556
        - 325
        - D7C3B8
        - 5
      - - 302
        - 322
        - 9D030D
        - 5
    reset_pos:
    - 548
    - 343
