cities:
  newdelsta:
    inn_pos: [645, 573] # 旅馆点
    entrance_pos: [337, 596] # 入口点
    reset_pos: [548,343] # 重置点,当小地图被遮挡时,遇到无法匹配到图标的时候,点击重置点
    backup_points: [ # 备份点,当逢魔点被遮挡时,遇到无法匹配到图标的时候,点击备份点
      [825,425],
      [759,671]
    ]
    check_points: [
      [533,617,0,0],
      [420,615,1,0],
      [576,443,0,1],
      [557,259,0,1],
      [677,257,0,1],
      # [675,327,0],
      [751,327,0,1],
      [815,324,0,1],
      [804,504,0,1],
      [720,500,0,1],
      [753,621,0,1],
      [647,619,0,1],
    ]