cities:
  newdelsta:
    inn_pos: [645, 573] # 旅馆点
    entrance_pos: [337, 596] # 入口点
    reset_pos: [548,343] # 重置点,当被遮挡时,遇到无法匹配到图标的时候,点击重置点
    backup_points: []
    check_points: [
      [533,617,0],
      [420,615,1],
      [576,443,0],
      [557,259,0],
      [677,257,0],
      [675,327,0],
      [751,327,0],
      [815,324,0],
      [804,504,0],
      [720,500,0],
      [753,621,0],
      [647,619,0],
    ]