cities:
  卡纳尔布来因:
    check_points:
    - id: 1
      item_pos:
      - backup_pos: []
        pos:
        - 643
        - 268
      next_point: true
      pos:
      - 610
      - 272
      reset_map: true
    - id: 2
      item_pos:
      - backup_pos: []
        pos:
        - 549
        - 353
      next_point: true
      pos:
      - 584
      - 314
      reset_map: true
    - id: 3
      item_pos:
      - backup_pos: []
        pos:
        - 854
        - 337
      next_point: true
      pos:
      - 672
      - 459
      reset_map: true
    - id: 4
      item_pos:
      - backup_pos: []
        pos:
        - 735
        - 235
      next_point: true
      pos:
      - 700
      - 534
      reset_map: true
    - id: 5
      item_pos:
      - backup_pos: []
        pos:
        - 806
        - 268
      next_point: true
      pos:
      - 810
      - 559
      reset_map: true
    - id: 6
      item_pos:
      - backup_pos: []
        pos:
        - 635
        - 245
      next_point: true
      pos:
      - 493
      - 493
      reset_map: true
    - id: 7
      item_pos:
      - backup_pos: []
        pos:
        - 419
        - 438
      next_point: true
      pos:
      - 442
      - 582
      reset_map: true
    - id: 8
      item_pos:
      - backup_pos: []
        pos:
        - 521
        - 264
      next_point: true
      pos:
      - 306
      - 523
      reset_map: true
    - id: 9
      item_pos:
      - backup_pos: []
        pos:
        - 639
        - 267
      next_point: true
      pos:
      - 341
      - 367
      reset_map: true
    - id: 10
      item_pos:
      - backup_pos: []
        pos:
        - 782
        - 414
      next_point: true
      pos:
      - 421
      - 365
      reset_map: true
    - id: 11
      item_pos:
      - backup_pos: []
        pos:
        - 784
        - 427
      next_point: true
      pos:
      - 530
      - 318
      reset_map: true
    - id: 12
      item_pos:
      - backup_pos: []
        pos:
        - 639
        - 311
      next_point: true
      pos:
      - 490
      - 129
      reset_map: true
    entrance_pos:
    - 658
    - 326
    inn_pos:
    - 383
    - 326
    monster_pos:
    - - 344
      - 433
    monsters:
    - battle_config: D:/dldbz/config/battle_scripts/卡纳尔布来因精英怪.txt
      name: 逢凶的海洋大蜥蜴人
    - battle_config: D:/dldbz/config/battle_scripts/卡纳尔布来因Boss.txt
      name: 逢虐的梅尔斯特罗姆
  托托哈哈岛:
    check_points:
    - id: 1
      item_pos:
      - backup_pos: []
        pos:
        - 522
        - 312
      next_point: true
      pos:
      - 773
      - 234
      reset_map: true
    - id: 2
      item_pos:
      - backup_pos: []
        pos:
        - 755
        - 344
      next_point: true
      pos:
      - 846
      - 300
      reset_map: true
    - id: 3
      item_pos:
      - backup_pos: []
        pos:
        - 852
        - 278
      - backup_pos: []
        pos:
        - 208
        - 457
      next_point: false
      pos:
      - 667
      - 314
      reset_map: true
    - id: 4
      item_pos:
      - backup_pos: []
        pos:
        - 802
        - 377
      next_point: true
      pos:
      - 583
      - 391
      reset_map: true
    - id: 5
      item_pos:
      - backup_pos: []
        pos:
        - 761
        - 429
      next_point: true
      pos:
      - 527
      - 429
      reset_map: true
    - id: 6
      item_pos:
      - backup_pos: []
        pos:
        - 629
        - 351
      next_point: true
      pos:
      - 292
      - 223
      reset_map: true
    - id: 7
      item_pos:
      - backup_pos: []
        pos:
        - 662
        - 212
      next_point: true
      pos:
      - 366
      - 371
      reset_map: true
    - id: 8
      item_pos:
      - backup_pos: []
        pos:
        - 515
        - 372
      next_point: true
      pos:
      - 363
      - 393
      reset_map: true
    - id: 9
      item_pos:
      - backup_pos: []
        pos:
        - 273
        - 313
      next_point: true
      pos:
      - 502
      - 444
      reset_map: true
    - id: 10
      item_pos:
      - backup_pos: []
        pos:
        - 358
        - 333
      - backup_pos: []
        pos:
        - 893
        - 357
      next_point: false
      pos:
      - 523
      - 588
      reset_map: true
    entrance_pos:
    - 736
    - 304
    inn_pos:
    - 467
    - 414
    monster_pos:
    - - 369
      - 422
    monsters:
    - battle_config: D:/dldbz/config/battle_scripts/托托哈哈岛精英怪.txt
      name: 逢凶的岛国大巨蛙
    - battle_config: D:/dldbz/config/battle_scripts/托托哈哈岛Boss.txt
      name: 逢虐的戴特摩尔
  新德尔斯塔:
    check_points:
    - id: 1
      item_pos:
      - backup_pos: []
        pos:
        - 1169
        - 280
      - backup_pos: []
        pos:
        - 316
        - 352
      next_point: false
      pos:
      - 420
      - 615
      reset_map: true
    - id: 2
      item_pos:
      - backup_pos: []
        pos:
        - 672
        - 362
      - backup_pos: []
        pos:
        - 862
        - 228
      next_point: false
      pos:
      - 486
      - 621
      reset_map: true
    - id: 3
      item_pos:
      - backup_pos: []
        pos:
        - 732
        - 378
      next_point: true
      pos:
      - 590
      - 444
      reset_map: true
    - id: 4
      item_pos:
      - backup_pos: []
        pos:
        - 69
        - 316
      next_point: true
      pos:
      - 557
      - 259
      reset_map: true
    - id: 5
      item_pos:
      - backup_pos: []
        pos:
        - 724
        - 321
      - backup_pos: []
        pos:
        - 507
        - 539
      next_point: false
      pos:
      - 675
      - 289
      reset_map: false
    - id: 6
      item_pos:
      - backup_pos: []
        pos:
        - 635
        - 397
      next_point: true
      pos:
      - 815
      - 324
      reset_map: true
    - id: 7
      item_pos:
      - backup_pos: []
        pos:
        - 868
        - 385
      next_point: true
      pos:
      - 804
      - 504
      reset_map: true
    - id: 8
      item_pos:
      - backup_pos: []
        pos:
        - 639
        - 357
      next_point: true
      pos:
      - 720
      - 500
      reset_map: true
    - id: 9
      item_pos:
      - backup_pos: []
        pos:
        - 623
        - 385
      next_point: true
      pos:
      - 753
      - 621
      reset_map: true
    - id: 10
      item_pos:
      - backup_pos: []
        pos:
        - 398
        - 420
      next_point: true
      pos:
      - 647
      - 619
      reset_map: true
    entrance_pos:
    - 337
    - 596
    inn_pos:
    - 645
    - 573
    monster_pos:
    - - 344
      - 433
    monsters:
    - battle_config: D:/dldbz/config/battle_scripts/1.txt
      name: 逢凶的城市大鼠人
    - battle_config: D:/dldbz/config/battle_scripts/1.txt
      name: 逢虐的基加提亚斯
